name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    
permissions:
  contents: read
  
jobs:
  sonar:
    name: Unit Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:          
          fetch-depth: 0
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: '20'

      - run: cd functions
      - run: npm ci
      - run: npm run build
      - run: npm run test:ci
